accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path("councils/", views.CouncilListView.as_view(), name="council_list"),
    path("councils/add/", views.CouncilCreateView.as_view(), name="create_council"),
    path(
        "councils/<int:pk>/edit/",
        views.CouncilUpdateView.as_view(),
        name="update_council",
    ),
    path("invite/", views.InviteCreateView.as_view(), name="create_invite"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/change/", views.PasswordChangeView.as_view(), name="edit_password"),
    path("password/reset/", views.PasswordResetView.as_view(), name="reset_password"),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/change/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("register/<token>/", views.registration, name="register"),
]

congresses/urls.py
from django.urls import path

from congresses import views
from excursions.views import create_order

app_name = "congresses"
urlpatterns = [
    path("<int:year>/", views.CongressDetailView.as_view(), name="congress_detail"),
    path(
        "<int:year>/add_attendance/",
        views.AttendanceCreateView.as_view(),
        name="create_attendance",
    ),
    path("attendances/", views.AttendanceListView.as_view(), name="attendance_list"),
    path(
        "attendances/export/",
        views.AttendanceExportView.as_view(),
        name="attendance_export",
    ),
    path(
        "attendances/<int:pk>/",
        views.AttendanceDetailsView.as_view(),
        name="attendance_detail",
    ),
    path(
        "attendances/<int:pk>/add_participant/",
        views.ParticipantCreateView.as_view(),
        name="create_participant",
    ),
    path(
        "participants/<int:pk>/add_portrait/",
        views.PortraitCreateView.as_view(),
        name="create_portrait",
    ),
    path("participants/<int:pk>/add_excursion/", create_order, name="create_order"),
    path("update_seats/", views.SeatFormView.as_view(), name="update_seats"),
]

fatama/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.flatpages import views

urlpatterns = [
    path("", views.flatpage, {"url": "/"}, name="landing_page"),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("congresses/", include("congresses.urls")),
    path("excursions/", include("excursions.urls")),
    path("privacy/", views.flatpage, {"url": "/privacy/"}, name="privacy"),
    path("site-notice/", views.flatpage, {"url": "/site-notice/"}, name="site_notice"),
    path("workshops/", include("workshops.urls")),
]

accounts/forms.py
import re
import secrets

from datetime import timedelta

from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.password_validation import password_validators_help_texts
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from accounts.models import Council, Invite, Profile
from fatama.forms import ModelForm, Form
from fatama.postmark import Mail


class AuthenticationForm(auth_forms.AuthenticationForm):
    template_name_label = "fatama/forms/label.html"

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        fields = {
            "username": "Benutzername",
            "password": "Passwort",
        }
        for field, label in fields.items():
            self.fields[field].widget.attrs.update({"class": "input"})
            self.fields[field].label = label

        self.error_messages.update(
            {
                "invalid_login": (
                    "Die Kombination aus Benutzername und Passwort ist ungültig. Beachte bitte, dass beide Felder die "
                    "Groß- und Kleinschreibung berücksichtigen."
                ),
                "inactive": "Dieses Konto ist inaktiv.",
            }
        )


class CouncilForm(ModelForm):
    class Meta:
        model = Council
        fields = ["university", "name"]
        widgets = {
            "university": forms.TextInput(attrs={"class": "input"}),
            "name": forms.TextInput(attrs={"class": "input"}),
        }

    def __init__(self, user, *args, **kwargs) -> None:
        self.user = user
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        council = super().save(commit=False)
        council.owner = self.user
        if commit:
            council.save()
        return council


class InviteForm(Form):
    emails = forms.CharField(
        label="E-Mail-Adressen",
        widget=forms.Textarea(attrs={"class": "textarea", "rows": 5}),
    )

    def __init__(self, user, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_emails(self) -> list[str]:
        data = self.cleaned_data["emails"]
        emails = [email.strip() for email in data.split(",")]
        for email in emails:
            try:
                validate_email(email)
            except ValidationError:
                raise ValidationError(
                    f"'{email}' ist keine gültige E-Mail-Adresse", code="invalid"
                )
        return emails

    @staticmethod
    def send_mail(request, invite: Invite) -> None:
        scheme = "https" if request.is_secure() else "http"
        host = request.get_host()
        path = reverse_lazy("accounts:register", kwargs={"token": invite.token})
        url = f"{scheme}://{host}{path}"

        context = {
            "action_url": url,
            "expired_at": invite.expired_at,
            "sender": invite.sender.get_full_name(),
        }

        mail = Mail(
            "invite",
            "Einladung zur FaTaMa",
            render_to_string("accounts/mails/invite.md", context, request),
            invite.recipient,
        )
        mail.send()

    def save(self, request) -> None:
        emails = self.cleaned_data["emails"]
        for email in emails:
            token = secrets.token_urlsafe(settings.INVITE_TOKEN_LENGTH)
            expired_at = timezone.now() + timedelta(days=settings.INVITE_EXPIRATION)
            invite = Invite.objects.create(
                token=token, recipient=email, sender=self.user, expired_at=expired_at
            )
            self.send_mail(request, invite)


class PasswordChangeForm(auth_forms.PasswordChangeForm):
    template_name_label = "fatama/forms/label.html"

    def __init__(self, user, *args, **kwargs) -> None:
        super().__init__(user, *args, **kwargs)
        fields = {
            "old_password": "Altes Passwort",
            "new_password1": "Neues Passwort",
            "new_password2": "Neues Passwort wiederholen",
        }
        for field, label in fields.items():
            self.fields[field].widget.attrs.update({"class": "input"})
            self.fields[field].label = label
        self.fields["new_password1"].help_text = "<br/>".join(
            [
                "Dein Passwort darf keine Ähnlichkeit zu anderen persönlichen Information aufweisen.",
                "Dein Passwort muss aus mindestens 8 Zeichen bestehen.",
                "Dein Passwort darf nicht zu offensichtlich sein.",
                "Dein Passwort darf nicht nur aus Ziffern bestehen.",
            ]
        )


class PasswordResetForm(auth_forms.PasswordResetForm):
    template_name_label = "fatama/forms/label.html"

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"class": "input"})
        self.fields["email"].label = "E-Mail-Adresse"

    def send_mail(self, *args, **kwargs) -> None:
        request = kwargs["request"]
        token_generator = kwargs["token_generator"]
        user = kwargs["user"]
        scheme = "https" if request.is_secure() else "http"
        host = request.get_host()
        path = reverse_lazy(
            "accounts:password_reset_confirm",
            kwargs={
                "uidb64": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": token_generator.make_token(user),
            },
        )
        url = f"{scheme}://{host}{path}"

        context = {"action_url": url, "user": user}

        mail = Mail(
            "password-reset",
            "Zurücksetzen deines Passworts",
            render_to_string("accounts/mails/password_reset.md", context, request),
            user.email,
        )
        mail.send()

    def save(self, *args, **kwargs):
        email = self.cleaned_data["email"]
        request = kwargs["request"]
        token_generator = kwargs["token_generator"]
        for user in self.get_users(email):
            self.send_mail(request=request, token_generator=token_generator, user=user)


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = []

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.user = self.user
        if commit:
            profile.save()
        return profile


class SetPasswordForm(auth_forms.SetPasswordForm):
    template_name_label = "fatama/forms/label.html"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["new_password1"].widget.attrs.update({"class": "input"})
        self.fields["new_password2"].widget.attrs.update({"class": "input"})
        self.fields["new_password1"].help_text = "<br>".join(
            password_validators_help_texts()
        )


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        labels = {
            "username": "Benutzername",
            "first_name": "Vorname",
            "last_name": "Nachname",
            "email": "E-Mail-Adresse",
        }
        widgets = {
            "username": forms.TextInput(attrs={"class": "input"}),
            "first_name": forms.TextInput(attrs={"class": "input"}),
            "last_name": forms.TextInput(attrs={"class": "input"}),
            "email": forms.EmailInput(attrs={"class": "input"}),
        }
        help_texts = {
            "username": "150 Zeichen oder weniger. Buchstaben und Ziffern sind zulässig.",
            "email": "Deine persönliche E-Mail-Adresse. Bitte nicht die E-Mail-Adresse der Fachschaft angeben.",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

    def clean_username(self):
        username = self.cleaned_data.get("username")
        match = re.match(r"^[a-z\d]+$", username, re.IGNORECASE)
        if not match:
            raise ValidationError(
                "Es sind nur Buchstaben und Ziffern erlaubt.", code="blocked_symbol"
            )
        return username

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth import logout, views as auth_views
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
)

from accounts.forms import (
    AuthenticationForm,
    CouncilForm,
    InviteForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
    UserForm,
)
from accounts.models import Council, Invite


class CouncilCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = CouncilForm
    success_message = "Gremium wurde erfolgreich erstellt."
    success_url = reverse_lazy("accounts:council_list")
    template_name = "accounts/council_form.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class CouncilListView(LoginRequiredMixin, ListView):
    model = Council


class CouncilUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    form_class = CouncilForm
    success_message = "Gremium wurde aktualisiert."
    success_url = reverse_lazy("accounts:council_list")
    template_name = "accounts/council_form.html"

    def get_object(self, queryset=None):
        council = get_object_or_404(Council, pk=self.kwargs["pk"])
        return council

    def get_form_kwargs(self):
        council = get_object_or_404(Council, pk=self.kwargs["pk"])
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": council.owner})
        return kwargs

    def test_func(self):
        council = get_object_or_404(Council, pk=self.kwargs["pk"])
        if self.request.user == council.owner:
            return True
        else:
            return False


class InviteCreateView(PermissionRequiredMixin, SuccessMessageMixin, FormView):
    form_class = InviteForm
    permission_required = "accounts.can_invite"
    template_name = "accounts/create_invite.html"
    success_url = reverse_lazy("accounts:create_invite")
    success_message = "Einladungen wurde per E-Mail verschickt."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["expiration"] = settings.INVITE_EXPIRATION
        return context

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save(self.request)
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    form_class = AuthenticationForm
    template_name = "accounts/login.html"


class LogoutView(auth_views.LogoutView):
    http_method_names = ["get", "post", "options"]
    next_page = reverse_lazy("accounts:login")
    template_name = "accounts/logout.html"

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return render(request, "accounts/logout.html")
        else:
            return redirect("accounts:login")


class PasswordChangeView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = PasswordChangeForm
    success_message = "Dein Password wurde aktualisiert."
    success_url = reverse_lazy("accounts:edit_password")
    template_name = "accounts/password_form.html"


class PasswordResetView(SuccessMessageMixin, auth_views.PasswordResetView):
    form_class = PasswordResetForm
    success_message = (
        "Eine E-Mail zum Zurücksetzen des Passworts wurde an <strong>%(email)s</strong> geschickt. Wenn "
        "innerhalb der nächsten 5 Minuten keine E-Mail zugestellt wurde existiert womöglich kein Konto "
        "mit dieser E-Mail-Adresse."
    )
    success_url = reverse_lazy("landing_page")
    template_name = "accounts/password_reset.html"


class PasswordResetConfirm(SuccessMessageMixin, auth_views.PasswordResetConfirmView):
    form_class = SetPasswordForm
    success_message = "Dein Passwort wurde erfolgreich geändert."
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/password_reset_confirm.html"


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"


def registration(request, token):
    invite = get_object_or_404(Invite, token=token)
    if invite.is_expired():
        raise PermissionDenied("Invite is expired.")
    if request.method == "POST":
        user_form = UserForm(data=request.POST, prefix="user")
        password_form = SetPasswordForm(data=request.POST, user=None, prefix="password")
        if user_form.is_valid() and password_form.is_valid():
            user = user_form.save()
            logout(request)
            invite.delete()

            password_form.user = user
            password_form.save()

            return redirect(reverse_lazy("accounts:login"))
    else:
        if request.user.is_authenticated:
            message = (
                "Aktuell ist der Benutzer "
                f"<strong>{request.user}</strong> angemeldet. Bei "
                "Abschluss der Registrierung wird der aktive Benutzer "
                "abgemeldet."
            )
            messages.warning(request, message)
        password_form = SetPasswordForm(None, prefix="password")
        user_form = UserForm(prefix="user")
    return render(
        request,
        "accounts/registration.html",
        {
            "password_form": password_form,
            "user_form": user_form,
        },
    )


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserForm
    success_message = "Deine Informationen wurden aktualisiert."
    success_url = reverse_lazy("accounts:profile")
    template_name = "accounts/user_form.html"

    def get_object(self, queryset=None):
        return self.request.user

accounts/templates/accounts/base.html
{% extends 'fatama/base.html' %}
{% load static %}
{% block content %}
<section class="section">
    <div class="container is-max-desktop">
        <div class="columns">
            <div class="column is-narrow">
                <aside class="menu" id="accountsMenu">
                    <p class="menu-label">Konto</p>
                    <ul class="menu-list">
                        <li>
                            <a href="{% url 'accounts:profile' %}">Profil</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:edit_password' %}">Passwort</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Abmelden</a>
                        </li>
                    </ul>
                    {% if user.is_staff %}
                    <p class="menu-label">Verwaltung</p>
                    <ul class="menu-list">
                        <li>
                            {% if perms.accounts.can_invite %}
                            <a href="{% url 'accounts:create_invite' %}">Einladen</a>
                            {% else %}
                            <a>
                                            <span class="icon-text">
                                                <span>Einladen</span>
                                                <span class="icon">
                                                    <i class="fa-solid fa-lock"></i>
                                                </span>
                                            </span>
                            </a>
                            {% endif %}
                        </li>
                        <li>
                            <a href="{% url 'congresses:attendance_list' %}">Teilnehmer</a>
                        </li>
                        <li>
                            <a href="{% url 'admin:index' %}">Administration</a>
                        </li>
                    </ul>
                    {% endif %}
                </aside>
            </div>
            <div class="column">
                {% block subcontent %}{% endblock %}
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ block.super }}
<script src="{% static 'accounts/js/active_menu.js' %}"></script>
{% endblock %}

accounts/templates/accounts/base_page.html
{% extends 'fatama/base.html' %}

{% block page %}
  <section class="section">
    <div class="container is-max-desktop">
      {% include 'fatama/messages.html' %}

      {% block content %}{% endblock %}
    </div>
  </section>
{% endblock %}

accounts/templates/accounts/council_detail.html
{% extends 'accounts/base.html' %}

{% block subcontent %}
    <h3 class="title">Gremium</h3>

    {% if user.council %}
        <p>{{ council.university }}</p>
        <p>{{ council.name }}</p>
    {% else %}
        <p class="block">Du hast noch kein Gremium erstellt.</p>
        <a href="{% url 'accounts:create_council' %}" class="button is-primary">
            Gremium erstellen
        </a>
    {% endif %}
{% endblock %}

accounts/templates/accounts/council_form.html
{% extends 'fatama/base.html' %}

{% block title %}
    {{ block.super }} | {% if form.initial %}Gremium bearbeiten{% else %}Gremium registrieren{% endif %}
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container is-max-desktop">
            <h3 class="title">
                {% if form.initial %}
                    Gremium bearbeiten
                {% else %}
                    Gremium registrieren
                {% endif %}
            </h3>
            {% if form.initial %}
                <h5 class="subtitle">Erstelle ein neues Gremium, welches dir zugeordnet wird</h5>
            {% endif %}

            <form method="post">
                {% csrf_token %}

                {{ form }}

                <div class="field is-grouped">
                    <div class="control">
                        <button type="submit" class="button is-primary">
                            {% if form.initial %}
                                Aktualisieren
                            {% else %}
                                Erstellen
                            {% endif %}
                        </button>
                    </div>
                    <div class="control">
                        <a href="{% url 'accounts:council_list' %}" class="button is-light">Abbrechen</a>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/council_list.html
{% extends 'fatama/base.html' %}

{% block title %}
    {{ block.super }} | Gremien
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container is-max-desktop">
            <h3 class="title">Gremien</h3>
            <h5 class="subtitle">Verzeichnis aller Gremien</h5>

            {% if user.council %}
                {% with user.council as council %}
                    <article class="message is-primary">
                        <div class="message-header">
                            Dein Gremium
                        </div>
                        <div class="message-body">
                            <div class="block">
                                <div class="icon-text">
                                    <span class="icon">
                                        <i class="fa-solid fa-university"></i>
                                    </span>
                                    <span>{{ council.university }}</span>
                                </div>
                                <div class="icon-text">
                                    <span class="icon">
                                        <i class="fa-solid fa-people-group"></i>
                                    </span>
                                    <span>{{ council.name }}</span>
                                </div>
                            </div>
                            <div class="buttons">
                                <a class="button is-primary" href="{% url 'accounts:update_council' council.pk %}">
                                    Gremium aktualisieren
                                </a>
                            </div>
                        </div>
                    </article>
                {% endwith %}
            {% else %}
                <article class="message is-warning">
                    <div class="message-header">
                        Benutzer ist keinem Gremium zugewiesen
                    </div>
                    <div class="message-body">
                        <div class="block">
                            Dein Konto ist noch keinem Gremium zugewiesen. Bitte lege ein neues Gremium an, da du dich
                            sonst zu keiner Tagung anmelden kannst. Wenn dein Gremium bereits im Verzeichnis aufgeführt
                            sein sollte, melde dich bei der austragenden Fachschaft, um das Gremium auf dich
                            umschreiben zu lassen.
                        </div>
                        <div class="buttons">
                            <a class="button is-warning" href="{% url 'accounts:create_council' %}">Gremium
                                erstellen</a>
                        </div>
                    </div>
                </article>
            {% endif %}

            {% regroup council_list by university as university_list %}
            {% for university, local_council_list in university_list %}
                <div class="block">
                    <p class="has-text-weight-bold">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="fa-solid fa-university"></i>
                            </span>
                            <span>{{ university }}</span>
                        </span>
                    </p>
                    {% for council in local_council_list %}
                        <p>
                            <span class="icon-text">
                                <span class="icon">
                                    <i class="fa-solid fa-people-group"></i>
                                </span>
                                <span>{{ council.name }}</span>
                            </span>

                            {% for year in council.get_years %}
                                <span class="tag">{{ year }}</span>
                            {% endfor %}
                        </p>
                    {% endfor %}
                </div>
            {% empty %}
                <article class="message is-info">
                    <div class="message-body">
                        Es wurden noch keine Gremien registriert.
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/create_invite.html
{% extends 'accounts/base.html' %}

{% block subcontent %}
    <h3 class="title">Einladung erstellen</h3>

    <article class="message is-info">
        <div class="message-body">
            Jeder Empfänger erhält eine individuelle E-Mail mit persönlichem
            Link zur Registrierung. Der Link ist für {{ expiration }} Tage
            gültig und kann einmalig zur Registrierung verwendet werden.
        </div>
    </article>

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button type="submit" class="button is-primary">Einladen</button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_page.html' %}

{% block title %}
    {{ block.super }} | Anmelden
{% endblock %}

{% block content %}
    <div class="columns is-centered">
        <div class="column is-half">
            <h3 class="title">Anmelden</h3>

            <form method="post">
                {% csrf_token %}

                {{ form }}

                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-primary" type="submit">Anmelden</button>
                    </div>
                    <div class="control">
                        <a class="button is-ghost" href="{% url 'accounts:reset_password' %}">
                            Passwort vergessen?
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block subcontent %}
    <h3 class="title">Abmelden</h3>

    <p class="block">Bitte bestätige, dass du dich abmelden möchtest.</p>

    <form method="post">
        {% csrf_token %}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-danger" type="submit">Abmelden</button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/password_form.html
{% extends 'accounts/base.html' %}

{% block title %}
    {{ block.super }} | Passwort ändern
{% endblock %}

{% block subcontent %}
    <h3 class="title">Passwort ändern</h3>

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">Passwort ändern</button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base_page.html' %}

{% block title %}
    {{ block.super }} | Passwort zurücksetzen
{% endblock %}

{% block content %}
    <div class="columns is-centered">
        <div class="column is-half">
            <h3 class="title">Passwort zurücksetzen</h3>

            <form method="post">
                {% csrf_token %}

                {{ form }}

                <div class="field is-grouped">
                    <div class="control">
                        <button type="submit" class="button is-primary">Link anfordern</button>
                    </div>
                    <div class="control">
                        <a class="button is-light" href="{% url 'accounts:login' %}">Abbrechen</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_page.html' %}

{% block content %}
    <h3 class="title">Passwort zurücksetzen</h3>
    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button type="submit" class="button is-primary">Ändern</button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block subcontent %}
    <div class="buttons is-pulled-right">
        <a class="button is-primary" href="{% url 'accounts:edit_profile' %}">Profil bearbeiten</a>
    </div>

    <h3 class="title">Profil</h3>

    <table class="table is-fullwidth">
        <tbody>
        <tr>
            <th>Benutzername</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Vor- und Nachname</th>
            <td>{{ user.get_full_name }}</td>
        </tr>
        <tr>
            <th>E-Mail-Adresse</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Beitrittsdatum</th>
            <td>{{ user.date_joined }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}