accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path("councils/", views.CouncilListView.as_view(), name="council_list"),
    path("councils/add/", views.CouncilCreateView.as_view(), name="create_council"),
    path(
        "councils/<int:pk>/edit/",
        views.CouncilUpdateView.as_view(),
        name="update_council",
    ),
    path("invite/", views.InviteCreateView.as_view(), name="create_invite"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/change/", views.PasswordChangeView.as_view(), name="edit_password"),
    path("password/reset/", views.PasswordResetView.as_view(), name="reset_password"),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/change/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("register/<token>/", views.registration, name="register"),
]

congresses/urls.py
from django.urls import path

from congresses import views
from excursions.views import create_order

app_name = "congresses"
urlpatterns = [
    path("<int:year>/", views.CongressDetailView.as_view(), name="congress_detail"),
    path(
        "<int:year>/add_attendance/",
        views.AttendanceCreateView.as_view(),
        name="create_attendance",
    ),
    path("attendances/", views.AttendanceListView.as_view(), name="attendance_list"),
    path(
        "attendances/export/",
        views.AttendanceExportView.as_view(),
        name="attendance_export",
    ),
    path(
        "attendances/<int:pk>/",
        views.AttendanceDetailsView.as_view(),
        name="attendance_detail",
    ),
    path(
        "attendances/<int:pk>/add_participant/",
        views.ParticipantCreateView.as_view(),
        name="create_participant",
    ),
    path(
        "participants/<int:pk>/add_portrait/",
        views.PortraitCreateView.as_view(),
        name="create_portrait",
    ),
    path("participants/<int:pk>/add_excursion/", create_order, name="create_order"),
    path("update_seats/", views.SeatFormView.as_view(), name="update_seats"),
]

excursions/urls.py
from django.urls import path

from excursions import views

app_name = "excursions"
urlpatterns = [
    path("", views.ExcursionListView.as_view(), name="excursion_list"),
]

fatama/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.flatpages import views

urlpatterns = [
    path("", views.flatpage, {"url": "/"}, name="landing_page"),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("congresses/", include("congresses.urls")),
    path("excursions/", include("excursions.urls")),
    path("privacy/", views.flatpage, {"url": "/privacy/"}, name="privacy"),
    path("site-notice/", views.flatpage, {"url": "/site-notice/"}, name="site_notice"),
    path("workshops/", include("workshops.urls")),
]

workshops/urls.py
from django.urls import path

from . import views

app_name = "workshops"
urlpatterns = [
    path("", views.WorkshopListView.as_view(), name="workshop_list"),
    path("add/", views.WorkshopCreateView.as_view(), name="create_workshop"),
]

fatama/forms.py
from django import forms
from django.forms.renderers import TemplatesSetting


class BulmaFormRenderer(TemplatesSetting):
    form_template_name = "fatama/form_snippet.html"
    formset_template_name = "fatama/formset_snippet.html"


class ModelForm(forms.ModelForm):
    template_name_label = "fatama/forms/label.html"


class Form(forms.Form):
    template_name_label = "fatama/forms/label.html"


class Select(forms.Select):
    template_name = "fatama/forms/widgets/select.html"


class FileInput(forms.FileInput):
    template_name = "fatama/forms/widgets/file.html"


class CheckboxInput(forms.CheckboxInput):
    template_name = "fatama/forms/widgets/checkbox.html"


class RadioSelect(forms.RadioSelect):
    template_name = "fatama/forms/widgets/radio.html"
    option_template_name = "fatama/forms/widgets/radio_option.html"

fatama/templates/fatama/base.html
<!DOCTYPE html>{% load static %}
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}FaTaMa {{ the_congress.year }}{% endblock %}</title>

    <!-- Bulma -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">

    <!-- Font Awesome -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
{% block page %}
    {% include 'fatama/navbar.html' %}

    {% if messages %}
        <section class="section">
            <div class="container is-max-desktop">
                {% include 'fatama/messages.html' %}
            </div>
        </section>
    {% endif %}

    {% block content %}{% endblock %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'fatama/js/burger.js' %}"></script>
    <script src="{% static 'fatama/js/active_menu.js' %}"></script>
{% endblock %}
</body>
</html>

fatama/templates/fatama/form_snippet.html
{% for error in form.non_field_errors %}
    <div class="notification is-danger">
        {{ error|safe }}
    </div>
{% endfor %}

{% for field in form %}
    <div class="field">
        {{ field.label_tag }}
        <div class="control">
            {{ field }}
        </div>
        <p class="help">
            {{ field.help_text|safe }}
        </p>
        {% for error in field.errors %}
            <p class="help is-danger">
                {{ error }}
            </p>
        {% endfor %}
    </div>
{% endfor %}

fatama/templates/fatama/formset_snippet.html
{{ formset.management_form }}

{% if formset.non_form_errors %}<div class="notification is-danger">{{ formset.non_form_errors }}</div>{% endif %}

{% for form in formset %}
    <fieldset>
        {{ form }}
    </fieldset>
{% endfor %}

fatama/templates/fatama/messages.html
{% for message in messages %}
    <div class="notification{% if message.tags %} {{ message.tags }}{% endif %}">
        {{ message|safe }}
    </div>
{% endfor %}

fatama/templates/fatama/messages_snippet.html
{% if messages %}
    {% for message in messages %}
        <div class="notification{% if message.tags %} {{ message.tags }}{% endif %}">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

fatama/templates/fatama/navbar.html
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">FaTaMa {{ the_congress.year }}</a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="mainNavbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="mainNavbar" class="navbar-menu">
            <div class="navbar-start">
                {% if user.is_authenticated %}
                    {% if the_congress %}
                        <a class="navbar-item" href="{% url 'congresses:congress_detail' the_congress.year %}">Tagung</a>
                    {% else %}
                        <div class="navbar-item has-text-grey-light">
                            <p class="icon-text">
                                <span class="icon">
                                    <i class="fa-solid fa-lock"></i>
                                </span>
                                <span>Tagung</span>
                            </p>
                        </div>
                    {% endif %}
                    <a class="navbar-item" href="{% url 'accounts:council_list' %}">Gremien</a>
                    <a class="navbar-item" href="{% url 'workshops:workshop_list' %}">Seminare</a>
                {% endif %}
                <a class="navbar-item" href="{% url 'excursions:excursion_list' %}">Exkursionen</a>
                <a class="navbar-item" target="_blank" href="https://wiki.fatama2024.de">
                    <span>Wiki</span>
                    <span class="icon">
                        <i class="fa-solid fa-arrow-up-right-from-square fa-sm"></i>
                    </span>
                </a>
            </div>
            <div class="navbar-end">
                {% if user.is_authenticated %}
                    <a class="navbar-item" href="{% url 'accounts:profile' %}">Konto</a>
                {% else %}
                    <a class="navbar-item" href="{% url 'accounts:login' %}">Anmelden</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>