fatama/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.flatpages import views

urlpatterns = [
    path("", views.flatpage, {"url": "/"}, name="landing_page"),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("congresses/", include("congresses.urls")),
    path("excursions/", include("excursions.urls")),
    path("privacy/", views.flatpage, {"url": "/privacy/"}, name="privacy"),
    path("site-notice/", views.flatpage, {"url": "/site-notice/"}, name="site_notice"),
    path("workshops/", include("workshops.urls")),
]

workshops/urls.py
from django.urls import path

from . import views

app_name = "workshops"
urlpatterns = [
    path("", views.WorkshopListView.as_view(), name="workshop_list"),
    path("add/", views.WorkshopCreateView.as_view(), name="create_workshop"),
]

workshops/models.py
from django.db import models
from django.db.models import CheckConstraint, Q

from accounts.models import User
from congresses.models import Congress
from fatama.templatetags.markdown import help_text


class Workshop(models.Model):
    SUGGESTED = "S"
    APPROVED = "A"
    REJECTED = "R"
    STATE_CHOICES = {
        SUGGESTED: "Vorgeschlagen",
        APPROVED: "Angenommen",
        REJECTED: "Abgelehnt",
    }
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_leader = models.BooleanField(
        "Redeleitung",
        default=True,
        help_text="Die Redeleitung für diesen Workshop übernehmen.",
    )
    title = models.CharField("Titel", max_length=200, unique=True)
    description = models.TextField("Beschreibung", help_text=help_text)
    state = models.CharField("Status", max_length=1, choices=STATE_CHOICES)
    comment = models.TextField("Kommentar", blank=True)
    congress = models.ForeignKey(
        Congress, on_delete=models.SET_NULL, blank=True, null=True
    )

    class Meta:
        verbose_name = "Seminar"
        verbose_name_plural = "Seminare"
        ordering = ["title"]
        constraints = [
            CheckConstraint(
                check=Q(state="S") | (Q(state="R") & ~Q(comment="")) | Q(state="A"),
                name="comment_when_rejected",
                violation_error_message="Bei Ablehnung ist eine Begründung anzugeben.",
            ),
        ]

    def __str__(self) -> str:
        return self.title

    def get_state_color(self) -> str:
        colors = {
            Workshop.SUGGESTED: "is-info",
            Workshop.APPROVED: "is-success",
            Workshop.REJECTED: "is-danger",
        }
        return colors[self.state]

workshops/forms.py
from django import forms

from fatama.forms import ModelForm, RadioSelect
from workshops.models import Workshop


class WorkshopForm(ModelForm):
    class Meta:
        model = Workshop
        fields = ["title", "description", "is_leader"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "input"}),
            "description": forms.Textarea(attrs={"class": "textarea"}),
            "is_leader": RadioSelect(choices=[(True, "Ja"), (False, "Nein")]),
        }

    def __init__(self, user, congress, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.congress = congress

    def save(self, commit: bool = True):
        workshop = super().save(commit=False)
        workshop.state = Workshop.SUGGESTED
        workshop.author = self.user
        workshop.congress = self.congress
        if commit:
            workshop.save()
        return workshop

workshops/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from congresses.models import Congress
from workshops.forms import WorkshopForm
from workshops.models import Workshop


class WorkshopCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = WorkshopForm
    template_name = "workshops/workshop_form.html"
    success_url = reverse_lazy("workshops:workshop_list")
    success_message = "Seminar wurde erstellt."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        congress = Congress.objects.order_by("-year").first()
        kwargs.update({"user": self.request.user, "congress": congress})
        return kwargs


class WorkshopListView(LoginRequiredMixin, ListView):
    model = Workshop

workshops/templates/workshops/workshop_form.html
{% extends "fatama/base.html" %}

{% block title %}
    {{ block.super }} | Seminar erstellen
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container is-max-desktop">
            <h3 class="title">Seminar erstellen</h3>
            <h5 class="subtitle">Neuen Vorschlag einreichen</h5>

            <form method="post">
                {% csrf_token %}

                {{ form }}

                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-primary" type="submit">Erstellen</button>
                    </div>
                    <div class="control">
                        <a class="button is-light" href="{% url 'workshops:workshop_list' %}">Abbrechen</a>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

workshops/templates/workshops/workshop_list.html
{% extends 'fatama/base.html' %}

{% load markdown %}

{% block title %}
    {{ block.super }} | Seminare
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container is-max-desktop">
            <h3 class="title">Seminare</h3>
            <h5 class="subtitle">Verzeichnis aller Seminare</h5>

            <article class="message is-primary">
                <div class="message-header">
                    Seminar erstellen
                </div>
                <div class="message-body">
                    <div class="block">
                        Hier kannst du Vorschläge für Seminare auf der Tagung einreichen. Die Vorschläge werden für
                        alle sichtbar sein und müssen durch die Organisatoren bestätigt werden.
                    </div>
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'workshops:create_workshop' %}">
                            Vorschlag einreichen
                        </a>
                    </div>
                </div>
            </article>

            {% for workshop in workshop_list %}
            <div class="block">
                <div class="is-pulled-right">
                    <span class="tag {{ workshop.get_state_color }}">{{ workshop.get_state_display }}</span>
                </div>

                <p class="has-text-weight-bold">{{ workshop }}</p>

                <div class="content">
                    {% render workshop.description %}
                </div>

                {% if workshop.comment %}
                    <p class="help is-danger">{{ workshop.comment }}</p>
                {% endif %}
            </div>
            {% empty %}
                <article class="message is-info">
                    <div class="message-body">
                        Es wurden noch keine Seminare eingereicht.
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>
{% endblock %}